spring:
  application:
    name: spring_docker_test_s1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.34.182.4:50406/docker
    username: mysqldocker
    password: mysqladmin
server:
  port: 8081