version: '3.2'

services:
  s1:
    image: s1
    container_name: s1
    ports:
      - "8081:8081"
    restart: always
    networks:
      docker-service-s1:
        ipv4_address: 172.26.0.3

  s2:
    image: s2
    container_name: s2
    ports:
      - "8082:8082"
    restart: always
    networks:
      docker-service-s2:
        ipv4_address: 172.27.0.3

  s1-nginx:
    image: nginx:latest
    container_name: s1-nginx
    restart: always
    ports:
      - "81:80"
    depends_on:
      - s1
    volumes:
      - ./s1/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      docker-service-s1:
        ipv4_address: 172.26.0.4

  s2-nginx:
    image: nginx:latest
    container_name: s2-nginx
    restart: always
    ports:
      - "82:80"
    depends_on:
      - s2
    volumes:
      - ./s2/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      docker-service-s2:
        ipv4_address: 172.27.0.4

networks:
  docker-service-s1:
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/16
  docker-service-s2:
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16
  docker-service-bridge:
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16
